import { useState, useEffect, useMemo } from 'react';
import { 
  ArrowLeft, 
  Save, 
  X, 
  CheckCircle2,
  Wallet as WalletIcon,
  Building2,
  CreditCard,
  PiggyBank
} from 'lucide-react';
import { cn } from '../../lib/utils';
import { CATEGORIES, MOCK_WALLETS } from '../../data/mockData';
import { Transaction, TransactionType, Wallet, FinanceSettings as FinanceType } from '../../types';

interface AddTransactionPageProps {
  transaction?: Transaction | null;
  initialDate?: string | null;
  wallets: Wallet[];
  financeSettings: FinanceType;
  onSave: (trn: Transaction) => void;
  onBack: () => void;
}

export default function AddTransactionPage({ transaction, initialDate, wallets, financeSettings, onSave, onBack }: AddTransactionPageProps) {
  const [type, setType] = useState<TransactionType>(transaction?.type || 'expense');
  const [date, setDate] = useState(transaction?.date || initialDate || new Date().toISOString().split('T')[0]);
  const [trnId, setTrnId] = useState(transaction?.trn_id || '');
  const [description, setDescription] = useState(transaction?.description || '');
  const [ref, setRef] = useState(transaction?.ref || '');
  const [category, setCategory] = useState(transaction?.category || '');
  const [party, setParty] = useState(transaction?.party || ''); // "From" or "To"
  const [selectedWallet, setSelectedWallet] = useState<string>(transaction?.wallet_id || wallets[0]?.id || '');
  const [amount, setAmount] = useState<string>(transaction?.amount.toString() || '');
  const [isSaving, setIsSaving] = useState(false);
  const [isSuccess, setIsSuccess] = useState(false);
  const [errors, setErrors] = useState<Record<string, string>>({});

  const currencySymbol = financeSettings.defaultCurrency.split('(')[1]?.replace(')', '') || '$';

  // Auto-generate Transaction ID ONLY if not editing
  useEffect(() => {
    if (!transaction) {
      const prefix = type === 'income' ? 'INC' : 'EXP';
      const random = Math.floor(Math.random() * 10000).toString().padStart(4, '0');
      setTrnId(`${prefix}-${date.replace(/-/g, '')}-${random}`);
    }
  }, [type, date, transaction]);

  // Reset category when type changes ONLY if not editing or if type changes during creation
  useEffect(() => {
    if (!transaction || (transaction && type !== transaction.type)) {
      setCategory(CATEGORIES[type][0]);
    }
  }, [type, transaction]);

  const validate = () => {
    const newErrors: Record<string, string> = {};
    if (!description.trim()) newErrors.description = 'Description is required';
    
    const amountNum = Number(amount);
    if (!amount || amountNum <= 0) {
      newErrors.amount = 'Valid amount is required';
    } else if (type === 'expense' && selectedWallet) {
      const wallet = wallets.find(w => w.id === selectedWallet);
      
      // If editing, we need to account for the original transaction amount being "returned" first
      let currentBalance = wallet?.balance || 0;
      if (transaction && transaction.wallet_id === selectedWallet) {
        currentBalance = transaction.type === 'income' 
          ? currentBalance - transaction.amount 
          : currentBalance + transaction.amount;
      }

      if (currentBalance < amountNum) {
        newErrors.amount = `Insufficient funds (Available: ${currencySymbol}${currentBalance.toLocaleString()})`;
      }
    }

    if (!selectedWallet) newErrors.wallet = 'Please select a wallet';
    if (!category) newErrors.category = 'Please select a category';
    
    setErrors(newErrors);
    return Object.keys(newErrors).length === 0;
  };

  const handleSave = () => {
    if (!validate()) return;

    const trn: Transaction = {
      trn_id: trnId,
      date,
      description: description.trim(),
      amount: Number(amount),
      category,
      type,
      wallet_id: selectedWallet,
      party: party.trim(),
      ref: ref.trim()
    };

    setIsSaving(true);
    // Simulate API call
    setTimeout(() => {
      setIsSaving(false);
      setIsSuccess(true);
      onSave(trn);
    }, 800);
  };

  const resetForm = () => {
    setDescription('');
    setRef('');
    setAmount('');
    setParty('');
    // trnId is auto-regenerated by useEffect
  };

  const walletIcons: Record<string, any> = {
    Wallet: WalletIcon,
    Bank: Building2,
    CreditCard: CreditCard,
    PiggyBank: PiggyBank
  };

  return (
    <div className="mx-auto max-w-2xl space-y-4 pb-24 md:space-y-8 md:pb-8">
      <header className="flex items-center gap-3 md:gap-4">
        <button 
          onClick={onBack}
          className="rounded-full p-2 text-zinc-500 hover:bg-zinc-100 dark:hover:bg-zinc-900"
        >
          <ArrowLeft className="h-5 w-5 md:h-6 md:w-6" />
        </button>
        <h1 className="text-xl font-bold tracking-tight text-zinc-900 dark:text-white md:text-3xl">
          {transaction ? 'Edit Transaction' : 'Add Transaction'}
        </h1>
      </header>

      <div className="rounded-2xl border border-zinc-200 bg-white p-4 shadow-sm dark:border-zinc-800 dark:bg-zinc-950 md:p-6">
        <div className="grid gap-4 md:gap-6">
          {/* Header row: ID and Date */}
          <div className="grid gap-4 sm:grid-cols-2">
            <div className="space-y-1">
              <label className="text-[10px] font-bold uppercase tracking-wider text-zinc-400">Transaction ID</label>
              <input
                type="text"
                readOnly
                value={trnId}
                className="w-full rounded-lg border border-zinc-200 bg-zinc-50 px-3 py-2 font-mono text-xs dark:border-zinc-800 dark:bg-zinc-900 dark:text-zinc-400 md:px-4 md:py-2.5 md:text-sm"
              />
            </div>
            <div className="space-y-1">
              <label className="text-[10px] font-bold uppercase tracking-wider text-zinc-400">Date</label>
              <input
                type="date"
                value={date}
                onChange={(e) => setDate(e.target.value)}
                className="w-full rounded-lg border border-zinc-200 bg-white px-3 py-2 text-xs outline-none focus:ring-2 focus:ring-emerald-500/20 dark:border-zinc-800 dark:bg-zinc-950 dark:text-white md:px-4 md:py-2.5 md:text-sm"
              />
            </div>
          </div>

          {/* Toggle: Income vs Expense */}
          <div className="flex rounded-xl bg-zinc-100 p-1 dark:bg-zinc-900">
            <button
              onClick={() => setType('expense')}
              className={cn(
                "flex-1 rounded-lg py-2 text-xs font-bold transition-all md:py-2.5 md:text-sm",
                type === 'expense'
                  ? "bg-rose-500 text-white shadow-lg shadow-rose-500/20"
                  : "text-zinc-500 hover:text-zinc-700 dark:text-zinc-400"
              )}
            >
              Expense
            </button>
            <button
              onClick={() => setType('income')}
              className={cn(
                "flex-1 rounded-lg py-2 text-xs font-bold transition-all md:py-2.5 md:text-sm",
                type === 'income'
                  ? "bg-emerald-500 text-white shadow-lg shadow-emerald-500/20"
                  : "text-zinc-500 hover:text-zinc-700 dark:text-zinc-400"
              )}
            >
              Income
            </button>
          </div>

          {/* Amount and Category */}
          <div className="grid gap-4 sm:grid-cols-2">
            <div className="space-y-1">
              <label className="text-[10px] font-bold uppercase tracking-wider text-zinc-400">Amount</label>
              <div className="relative">
                <span className="absolute left-3 top-1/2 -translate-y-1/2 text-xs text-zinc-400 md:left-4 md:text-sm">{currencySymbol}</span>
                <input
                  type="number"
                  placeholder="0.00"
                  value={amount}
                  onChange={(e) => {
                    setAmount(e.target.value);
                    if (errors.amount) setErrors({ ...errors, amount: '' });
                  }}
                  className={cn(
                    "w-full rounded-lg border bg-white py-2 pl-7 pr-3 text-xs outline-none focus:ring-2 focus:ring-emerald-500/20 dark:bg-zinc-950 dark:text-white md:py-2.5 md:pl-8 md:pr-4 md:text-sm",
                    errors.amount ? "border-rose-500 focus:ring-rose-500/20" : "border-zinc-200 dark:border-zinc-800"
                  )}
                />
              </div>
              {errors.amount && <p className="text-[10px] font-bold text-rose-500 uppercase">{errors.amount}</p>}
            </div>
            <div className="space-y-1">
              <label className="text-[10px] font-bold uppercase tracking-wider text-zinc-400">Category</label>
              <select
                value={category}
                onChange={(e) => {
                  setCategory(e.target.value);
                  if (errors.category) setErrors({ ...errors, category: '' });
                }}
                className={cn(
                  "w-full rounded-lg border bg-white px-3 py-2 text-xs outline-none focus:ring-2 focus:ring-emerald-500/20 dark:bg-zinc-950 dark:text-white md:px-4 md:py-2.5 md:text-sm",
                  errors.category ? "border-rose-500 focus:ring-rose-500/20" : "border-zinc-200 dark:border-zinc-800"
                )}
              >
                {CATEGORIES[type].map(c => (
                  <option key={c} value={c}>{c}</option>
                ))}
              </select>
              {errors.category && <p className="text-[10px] font-bold text-rose-500 uppercase">{errors.category}</p>}
            </div>
          </div>

          {/* Description and Ref */}
          <div className="grid gap-4">
            <div className="space-y-1">
              <label className="text-[10px] font-bold uppercase tracking-wider text-zinc-400">Description</label>
              <input
                type="text"
                placeholder="What was this for?"
                value={description}
                onChange={(e) => {
                  setDescription(e.target.value);
                  if (errors.description) setErrors({ ...errors, description: '' });
                }}
                className={cn(
                  "w-full rounded-lg border bg-white px-3 py-2 text-xs outline-none focus:ring-2 focus:ring-emerald-500/20 dark:bg-zinc-950 dark:text-white md:px-4 md:py-2.5 md:text-sm",
                  errors.description ? "border-rose-500 focus:ring-rose-500/20" : "border-zinc-200 dark:border-zinc-800"
                )}
              />
              {errors.description && <p className="text-[10px] font-bold text-rose-500 uppercase">{errors.description}</p>}
            </div>
            <div className="grid gap-4 sm:grid-cols-2">
              <div className="space-y-1">
                <label className="text-[10px] font-bold uppercase tracking-wider text-zinc-400">Ref / Note</label>
                <input
                  type="text"
                  placeholder="Reference #"
                  value={ref}
                  onChange={(e) => setRef(e.target.value)}
                  className="w-full rounded-lg border border-zinc-200 bg-white px-3 py-2 text-xs outline-none focus:ring-2 focus:ring-emerald-500/20 dark:border-zinc-800 dark:bg-zinc-950 dark:text-white md:px-4 md:py-2.5 md:text-sm"
                />
              </div>
              <div className="space-y-1">
                <label className="text-[10px] font-bold uppercase tracking-wider text-zinc-400">
                  {type === 'expense' ? 'Paid From' : 'Received In'}
                </label>
                <input
                  type="text"
                  placeholder={type === 'expense' ? 'Vendor / Person' : 'Source / Person'}
                  value={party}
                  onChange={(e) => setParty(e.target.value)}
                  className="w-full rounded-lg border border-zinc-200 bg-white px-3 py-2 text-xs outline-none focus:ring-2 focus:ring-emerald-500/20 dark:border-zinc-800 dark:bg-zinc-950 dark:text-white md:px-4 md:py-2.5 md:text-sm"
                />
              </div>
            </div>
          </div>

          {/* Wallet Selection */}
          <div className="space-y-2">
            <label className="text-[10px] font-bold uppercase tracking-wider text-zinc-400">Select Wallet</label>
            <div className="grid grid-cols-2 gap-2 sm:grid-cols-4 md:gap-3">
              {wallets.map((wallet) => {
                const Icon = walletIcons[wallet.type === 'bank' ? 'Bank' : 'Wallet'] || WalletIcon;
                const amountNum = Number(amount) || 0;
                
                // Calculate available balance for this wallet
                let availableBalance = wallet.balance;
                if (transaction && transaction.wallet_id === wallet.id) {
                  availableBalance = transaction.type === 'income' 
                    ? wallet.balance - transaction.amount 
                    : wallet.balance + transaction.amount;
                }
                
                const isInsufficient = type === 'expense' && amountNum > availableBalance;

                return (
                  <button
                    key={wallet.id}
                    onClick={() => setSelectedWallet(wallet.id)}
                    className={cn(
                      "flex flex-col items-center justify-center rounded-xl border p-3 transition-all relative overflow-hidden",
                      selectedWallet === wallet.id
                        ? "border-emerald-500 bg-emerald-50 dark:bg-emerald-500/10"
                        : isInsufficient
                          ? "border-rose-200 bg-rose-50/50 dark:border-rose-900/30 dark:bg-rose-900/10"
                          : "border-zinc-200 hover:bg-zinc-50 dark:border-zinc-800 dark:hover:bg-zinc-900"
                    )}
                  >
                    {isInsufficient && (
                      <div className="absolute top-0 right-0 p-1">
                        <div className="h-1.5 w-1.5 rounded-full bg-rose-500 animate-pulse" />
                      </div>
                    )}
                    <Icon className={cn(
                      "mb-2 h-5 w-5",
                      selectedWallet === wallet.id ? "text-emerald-600 dark:text-emerald-400" : isInsufficient ? "text-rose-400" : "text-zinc-400"
                    )} />
                    <span className="text-[10px] font-bold uppercase tracking-wider text-zinc-500 truncate w-full text-center px-1">
                      {wallet.name || wallet.bankName}
                    </span>
                    <span className={cn(
                      "mt-1 text-xs font-semibold",
                      isInsufficient ? "text-rose-600 dark:text-rose-400" : "text-zinc-900 dark:text-white"
                    )}>
                      {currencySymbol}{wallet.balance.toLocaleString()}
                    </span>
                    {isInsufficient && (
                      <span className="mt-0.5 text-[8px] font-bold text-rose-500 uppercase">Low Funds</span>
                    )}
                  </button>
                );
              })}
            </div>
          </div>

          {/* Actions */}
          <div className="flex gap-4 pt-4">
            <button
              onClick={onBack}
              className="flex flex-1 items-center justify-center gap-2 rounded-xl border border-zinc-200 bg-white py-3 text-sm font-bold text-zinc-700 hover:bg-zinc-50 dark:border-zinc-800 dark:bg-zinc-950 dark:text-zinc-300 dark:hover:bg-zinc-900"
            >
              <X className="h-4 w-4" />
              Cancel
            </button>
            <button
              onClick={handleSave}
              disabled={isSaving || isSuccess}
              className="flex flex-1 items-center justify-center gap-2 rounded-xl bg-zinc-900 py-3 text-sm font-bold text-white shadow-lg hover:bg-zinc-800 disabled:opacity-50 dark:bg-emerald-600 dark:hover:bg-emerald-700"
            >
              {isSaving ? (
                <div className="h-5 w-5 animate-spin rounded-full border-2 border-white border-t-transparent" />
              ) : isSuccess ? (
                <>
                  <CheckCircle2 className="h-5 w-5" />
                  Saved!
                </>
              ) : (
                <>
                  <Save className="h-5 w-5" />
                  Save Transaction
                </>
              )}
            </button>
          </div>
        </div>
      </div>

      {isSuccess && (
        <div className="flex items-center justify-center rounded-xl bg-emerald-500/10 p-4 text-emerald-600 dark:text-emerald-400">
          <CheckCircle2 className="mr-2 h-5 w-5" />
          Transaction added successfully. Preparing form for new entry...
        </div>
      )}
    </div>
  );
}
