import { useState, useEffect, useMemo } from 'react';
import { 
  ArrowLeft, 
  Save, 
  X, 
  CheckCircle2,
  Wallet as WalletIcon,
  Building2,
  CreditCard,
  PiggyBank
} from 'lucide-react';
import { cn } from '../lib/utils';
import { CATEGORIES, MOCK_WALLETS } from '../mockData';
import { Transaction, TransactionType, Wallet, FinanceSettings as FinanceType } from '../types';

interface AddTransactionPageProps {
  transaction?: Transaction | null;
  initialDate?: string | null;
  wallets: Wallet[];
  financeSettings: FinanceType;
  onSave: (trn: Transaction) => void;
  onBack: () => void;
}

export default function AddTransactionPage({ transaction, initialDate, wallets, financeSettings, onSave, onBack }: AddTransactionPageProps) {
  const [type, setType] = useState<TransactionType>(transaction?.type || 'expense');
  const [date, setDate] = useState(transaction?.date || initialDate || new Date().toISOString().split('T')[0]);
  const [trnId, setTrnId] = useState(transaction?.trn_id || '');
  const [description, setDescription] = useState(transaction?.description || '');
  const [ref, setRef] = useState(transaction?.ref || '');
  const [category, setCategory] = useState(transaction?.category || '');
  const [party, setParty] = useState(transaction?.party || ''); // "From" or "To"
  const [selectedWallet, setSelectedWallet] = useState<string>(transaction?.wallet_id || wallets[0]?.id || '');
  const [amount, setAmount] = useState<string>(transaction?.amount.toString() || '');
  const [isSaving, setIsSaving] = useState(false);
  const [isSuccess, setIsSuccess] = useState(false);
  const [errors, setErrors] = useState<Record<string, string>>({});

  const currencySymbol = financeSettings.defaultCurrency.split('(')[1]?.replace(')', '') || '$';

  // Auto-generate Transaction ID ONLY if not editing
  useEffect(() => {
    if (!transaction) {
      const prefix = type === 'income' ? 'INC' : 'EXP';
      const random = Math.floor(Math.random() * 10000).toString().padStart(4, '0');
      setTrnId(`${prefix}-${date.replace(/-/g, '')}-${random}`);
    }
  }, [type, date, transaction]);

  // Reset category when type changes ONLY if not editing or if type changes during creation
  useEffect(() => {
    if (!transaction || (transaction && type !== transaction.type)) {
      setCategory(CATEGORIES[type][0]);
    }
  }, [type, transaction]);

  const validate = () => {
    const newErrors: Record<string, string> = {};
    if (!description.trim()) newErrors.description = 'Description is required';
    if (!amount || Number(amount) <= 0) newErrors.amount = 'Valid amount is required';
    if (!selectedWallet) newErrors.wallet = 'Please select a wallet';
    if (!category) newErrors.category = 'Please select a category';
    
    setErrors(newErrors);
    return Object.keys(newErrors).length === 0;
  };

  const handleSave = () => {
    if (!validate()) return;

    const trn: Transaction = {
      trn_id: trnId,
      date,
      description: description.trim(),
      amount: Number(amount),
      category,
      type,
      wallet_id: selectedWallet,
      party: party.trim(),
      ref: ref.trim()
    };

    setIsSaving(true);
    // Simulate API call
    setTimeout(() => {
      setIsSaving(false);
      setIsSuccess(true);
      onSave(trn);
    }, 800);
  };

  const resetForm = () => {
    setDescription('');
    setRef('');
    setAmount('');
    setParty('');
    // trnId is auto-regenerated by useEffect
  };

  const walletIcons: Record<string, any> = {
    Wallet: WalletIcon,
    Bank: Building2,
    CreditCard: CreditCard,
    PiggyBank: PiggyBank
  };

  return (
    <div className="mx-auto max-w-2xl space-y-8 pb-24 md:pb-8">
      <header className="flex items-center gap-4">
        <button 
          onClick={onBack}
          className="rounded-full p-2 text-zinc-500 hover:bg-zinc-100 dark:hover:bg-zinc-900"
        >
          <ArrowLeft className="h-6 w-6" />
        </button>
        <h1 className="text-3xl font-bold tracking-tight text-zinc-900 dark:text-white">
          {transaction ? 'Edit Transaction' : 'Add Transaction'}
        </h1>
      </header>

      <div className="rounded-2xl border border-zinc-200 bg-white p-6 shadow-sm dark:border-zinc-800 dark:bg-zinc-950">
        <div className="grid gap-6">
          {/* Header row: ID and Date */}
          <div className="grid gap-4 sm:grid-cols-2">
            <div className="space-y-1.5">
              <label className="text-sm font-medium text-zinc-500">Transaction ID</label>
              <input
                type="text"
                readOnly
                value={trnId}
                className="w-full rounded-lg border border-zinc-200 bg-zinc-50 px-4 py-2.5 font-mono text-sm dark:border-zinc-800 dark:bg-zinc-900 dark:text-zinc-400"
              />
            </div>
            <div className="space-y-1.5">
              <label className="text-sm font-medium text-zinc-500">Date</label>
              <input
                type="date"
                value={date}
                onChange={(e) => setDate(e.target.value)}
                className="w-full rounded-lg border border-zinc-200 bg-white px-4 py-2.5 text-sm outline-none focus:ring-2 focus:ring-emerald-500/20 dark:border-zinc-800 dark:bg-zinc-950 dark:text-white"
              />
            </div>
          </div>

          {/* Toggle: Income vs Expense */}
          <div className="flex rounded-xl bg-zinc-100 p-1 dark:bg-zinc-900">
            <button
              onClick={() => setType('expense')}
              className={cn(
                "flex-1 rounded-lg py-2.5 text-sm font-bold transition-all",
                type === 'expense'
                  ? "bg-rose-500 text-white shadow-lg shadow-rose-500/20"
                  : "text-zinc-500 hover:text-zinc-700 dark:text-zinc-400"
              )}
            >
              Expense
            </button>
            <button
              onClick={() => setType('income')}
              className={cn(
                "flex-1 rounded-lg py-2.5 text-sm font-bold transition-all",
                type === 'income'
                  ? "bg-emerald-500 text-white shadow-lg shadow-emerald-500/20"
                  : "text-zinc-500 hover:text-zinc-700 dark:text-zinc-400"
              )}
            >
              Income
            </button>
          </div>

          {/* Amount and Category */}
          <div className="grid gap-4 sm:grid-cols-2">
            <div className="space-y-1.5">
              <label className="text-sm font-medium text-zinc-500">Amount</label>
              <div className="relative">
                <span className="absolute left-4 top-1/2 -translate-y-1/2 text-zinc-400">{currencySymbol}</span>
                <input
                  type="number"
                  placeholder="0.00"
                  value={amount}
                  onChange={(e) => {
                    setAmount(e.target.value);
                    if (errors.amount) setErrors({ ...errors, amount: '' });
                  }}
                  className={cn(
                    "w-full rounded-lg border bg-white py-2.5 pl-8 pr-4 text-sm outline-none focus:ring-2 focus:ring-emerald-500/20 dark:bg-zinc-950 dark:text-white",
                    errors.amount ? "border-rose-500 focus:ring-rose-500/20" : "border-zinc-200 dark:border-zinc-800"
                  )}
                />
              </div>
              {errors.amount && <p className="text-[10px] font-bold text-rose-500 uppercase">{errors.amount}</p>}
            </div>
            <div className="space-y-1.5">
              <label className="text-sm font-medium text-zinc-500">Category</label>
              <select
                value={category}
                onChange={(e) => {
                  setCategory(e.target.value);
                  if (errors.category) setErrors({ ...errors, category: '' });
                }}
                className={cn(
                  "w-full rounded-lg border bg-white px-4 py-2.5 text-sm outline-none focus:ring-2 focus:ring-emerald-500/20 dark:bg-zinc-950 dark:text-white",
                  errors.category ? "border-rose-500 focus:ring-rose-500/20" : "border-zinc-200 dark:border-zinc-800"
                )}
              >
                {CATEGORIES[type].map(c => (
                  <option key={c} value={c}>{c}</option>
                ))}
              </select>
              {errors.category && <p className="text-[10px] font-bold text-rose-500 uppercase">{errors.category}</p>}
            </div>
          </div>

          {/* Description and Ref */}
          <div className="grid gap-4">
            <div className="space-y-1.5">
              <label className="text-sm font-medium text-zinc-500">Description</label>
              <input
                type="text"
                placeholder="What was this for?"
                value={description}
                onChange={(e) => {
                  setDescription(e.target.value);
                  if (errors.description) setErrors({ ...errors, description: '' });
                }}
                className={cn(
                  "w-full rounded-lg border bg-white px-4 py-2.5 text-sm outline-none focus:ring-2 focus:ring-emerald-500/20 dark:bg-zinc-950 dark:text-white",
                  errors.description ? "border-rose-500 focus:ring-rose-500/20" : "border-zinc-200 dark:border-zinc-800"
                )}
              />
              {errors.description && <p className="text-[10px] font-bold text-rose-500 uppercase">{errors.description}</p>}
            </div>
            <div className="grid gap-4 sm:grid-cols-2">
              <div className="space-y-1.5">
                <label className="text-sm font-medium text-zinc-500">Ref / Note</label>
                <input
                  type="text"
                  placeholder="Reference #"
                  value={ref}
                  onChange={(e) => setRef(e.target.value)}
                  className="w-full rounded-lg border border-zinc-200 bg-white px-4 py-2.5 text-sm outline-none focus:ring-2 focus:ring-emerald-500/20 dark:border-zinc-800 dark:bg-zinc-950 dark:text-white"
                />
              </div>
              <div className="space-y-1.5">
                <label className="text-sm font-medium text-zinc-500">
                  {type === 'expense' ? 'Paid From' : 'Received In'}
                </label>
                <input
                  type="text"
                  placeholder={type === 'expense' ? 'Vendor / Person' : 'Source / Person'}
                  value={party}
                  onChange={(e) => setParty(e.target.value)}
                  className="w-full rounded-lg border border-zinc-200 bg-white px-4 py-2.5 text-sm outline-none focus:ring-2 focus:ring-emerald-500/20 dark:border-zinc-800 dark:bg-zinc-950 dark:text-white"
                />
              </div>
            </div>
          </div>

          {/* Wallet Selection */}
          <div className="space-y-3">
            <label className="text-sm font-medium text-zinc-500">Select Wallet</label>
            <div className="grid grid-cols-2 gap-3 sm:grid-cols-4">
              {wallets.map((wallet) => {
                const Icon = walletIcons[wallet.type === 'bank' ? 'Bank' : 'Wallet'] || WalletIcon;
                return (
                  <button
                    key={wallet.id}
                    onClick={() => setSelectedWallet(wallet.id)}
                    className={cn(
                      "flex flex-col items-center justify-center rounded-xl border p-3 transition-all",
                      selectedWallet === wallet.id
                        ? "border-emerald-500 bg-emerald-50 dark:bg-emerald-500/10"
                        : "border-zinc-200 hover:bg-zinc-50 dark:border-zinc-800 dark:hover:bg-zinc-900"
                    )}
                  >
                    <Icon className={cn(
                      "mb-2 h-5 w-5",
                      selectedWallet === wallet.id ? "text-emerald-600 dark:text-emerald-400" : "text-zinc-400"
                    )} />
                    <span className="text-[10px] font-bold uppercase tracking-wider text-zinc-500 truncate w-full text-center px-1">
                      {wallet.name || wallet.bankName}
                    </span>
                    <span className="mt-1 text-xs font-semibold text-zinc-900 dark:text-white">
                      {currencySymbol}{wallet.balance.toLocaleString()}
                    </span>
                  </button>
                );
              })}
            </div>
          </div>

          {/* Actions */}
          <div className="flex gap-4 pt-4">
            <button
              onClick={onBack}
              className="flex flex-1 items-center justify-center gap-2 rounded-xl border border-zinc-200 bg-white py-3 text-sm font-bold text-zinc-700 hover:bg-zinc-50 dark:border-zinc-800 dark:bg-zinc-950 dark:text-zinc-300 dark:hover:bg-zinc-900"
            >
              <X className="h-4 w-4" />
              Cancel
            </button>
            <button
              onClick={handleSave}
              disabled={isSaving || isSuccess}
              className="flex flex-1 items-center justify-center gap-2 rounded-xl bg-zinc-900 py-3 text-sm font-bold text-white shadow-lg hover:bg-zinc-800 disabled:opacity-50 dark:bg-emerald-600 dark:hover:bg-emerald-700"
            >
              {isSaving ? (
                <div className="h-5 w-5 animate-spin rounded-full border-2 border-white border-t-transparent" />
              ) : isSuccess ? (
                <>
                  <CheckCircle2 className="h-5 w-5" />
                  Saved!
                </>
              ) : (
                <>
                  <Save className="h-5 w-5" />
                  Save Transaction
                </>
              )}
            </button>
          </div>
        </div>
      </div>

      {isSuccess && (
        <div className="flex items-center justify-center rounded-xl bg-emerald-500/10 p-4 text-emerald-600 dark:text-emerald-400">
          <CheckCircle2 className="mr-2 h-5 w-5" />
          Transaction added successfully. Preparing form for new entry...
        </div>
      )}
    </div>
  );
}
